server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HuynhNgocHieu/config
          //uri: https://gcsgit.cybersoft-vn.com/EMB/automotive/blob/hieuhuynhvehicle/spring-cloud-config